# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: gcr.io/km1-runcloud/nginx:v2
#         ports:
#         - containerPort: 80

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svcc
#   labels:
#    app: nginx
# spec:
#   type: NodePort
#   selector:
#     app: nginx
#   ports:
#   - name: http
#     port: 80
#     targetPort: 8080     


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      volumes:
      - name: index-html
        emptyDir: {}
      initContainers:
      - name: setup
        image: europe-west8-docker.pkg.dev/km1-runcloud/charan-nginx/new-nginx:v2
        command:
        - /bin/sh
        - -c
        - echo kubernetes works > /task-dir/index.html
        volumeMounts:
        - name: index-html
          mountPath: "/task-dir"
      containers:
      - name: nginx
        image: nginx:mainline
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html/customdir
---
# next, a service is required to handle traffic to the pods created by the deployment

apiVersion: v1
kind: Service
metadata:
  name: nginx-server-service
  labels:
    tier: networking
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-server
  type: ClusterIP
